# Generated by Django 4.2.2 on 2023-07-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberId', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=50)),
                ('Group_Name', models.CharField(max_length=300)),
                ('etc', models.CharField(max_length=300)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
            ],
            options={
                'db_table': 'Line_Memebers',
            },
        ),
    ]
